name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          path: "src"

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build Plugins
        run: |
          cd src
          # Lista completa de proveedores no refactorizados para KuroStream
          rm -rf PeliculasFlixProvider/ PelispediaProvider/ Pelisplus4KProvider/ PelisplusHDProvider/ PelisplusSOProvider/ PlayhubProvider/ SeriesflixProvider/ SeriesMetroProvider/ SoloLatinoProvider/ TioAnimeProvider/ AnimensionProvider/ AnimeflvProvider/ AnimeflvIOProvider/ AnimeJlProvider/ AniwatchProvider/ AniwaveProvider/ BflixProvider/ CablevisionHdProvider/ CinecalidadProvider/ CuevanaProvider/ ComamosRamenProvider/ DoramasytProvider/ EstrenosDoramasProvider/ IdonehdProvider/ InkapelisProvider/ JkanimeProvider/ MonoschinosProvider/
          
          chmod +x gradlew
          ./gradlew make makePluginsJson
          mkdir -p ../dist
          cp build/plugins.json ../dist/
          cp **/build/*.cs3 ../dist/ 2>/dev/null || true

      - name: Deploy to Builds Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: builds
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
